### ISSUE TITLE
Update: strip down initial template

### ISSUE THREAD

**Issue by sauravhiremath** [MLH-Fellowship/0.4.1-Executely-server#2]
- [ ] TS support, compiled with babel preferably.
- [ ] Remove unnecessary modules
- [ ] ESLint config (TBD) - Remove the current TSLint config (deprecated)
- [ ] Jest config (TBD)

Feel free to discuss below if you have any additional suggestions :)

**Comment by YashKumarVerma** [comment]
How about using 2 spaces instead :smile:
